### ISSUE TITLE
error: there is no package called ‘CAT’

### ISSUE THREAD

**Issue by Wong718** [tzhu-bio/cisDynet#5]
Hello, I have encountered some problems when I tried to install cisDynet.
The log file shown is:
Error: package or namespace load failed for ‘cisDynet’:
 .onLoad failed in loadNamespace() for 'cisDynet', details:
  call: packageVersion("CAT")
  error: there is no package called ‘CAT’
And I used install.packages('cat') to install a package named 'cat' but it didn't work.

Your package is useful for analysis ATAC-seq, and I am looking forward to your response, thanks.

**Comment by tzhu-bio** [comment]
Please try it again!
